# These are the settings that tend to differ between installations. Tweak these for your installation.
# Copyright (C) 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is an API key generated by Ade Oshineye. 
# Please don't use it or you'll find that your app runs out of quota because 
# you're sharing that quota with the world. Instead you should generate your own at:
# https://code.google.com/apis/console
API_KEY = 'AIzaSyDSMX3UNdWWobl3k_eml_yAXfmJZzldfLg'


# OAuth consumer key and secret
# Go here: https://www.google.com/accounts/ManageDomains and register your instance so that
# you'll get your own consumer key and consumer secret
CONSUMER_KEY = 'anonymous'
CONSUMER_SECRET = 'anonymous'

DISPLAY_NAME = 'OAuth Is A 4 Letter Word'

# Installation specific config ends.
